# Generated by Django 4.2.4 on 2023-08-10 15:14

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
    ]
